version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: techx-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techx-api
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

volumes:
  db_data:
